version: '3.4'

services:
  notes-back:
    container_name: notes-back
    image: ethanmars56/notesback
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - AppSettings__JwtSettings__Issuer=${AppSettings__JwtSettings__Issuer}
      - AppSettings__JwtSettings__Audience=${AppSettings__JwtSettings__Audience}
      - AppSettings__JwtSettings__Key=${AppSettings__JwtSettings__Key}
      - ConnectionStrings__NotesDatabase=${ConnectionStrings__NotesDatabase}
    build:
      context: .
      dockerfile: NotesBack/Dockerfile
    depends_on:
      - notes-db
  notes-db:
    container_name: notes-db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - /home/docker-volumes/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  notes-front:
    container_name: notes-front
    image: ethanmars56/notesfront
    build:
      context: .
      dockerfile: notes-front/Dockerfile
    depends_on:
      - notes-back
    ports:
      - 80:80