name: deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on:
      - self-hosted
    steps:
      - name: checkout repos
        uses: actions/checkout@v3
      - name: stop and remove containers
        run: |
           ls -la
           docker-compose down
      - name: remove images
        run: |
          docker image rm $(docker images) || true
      - name: set up environment variables
        run: |
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> $GITHUB_ENV
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> $GITHUB_ENV
          echo "AppSettings__JwtSettings__Issuer=${{ secrets.AppSettings__JwtSettings__Issuer }}" >> $GITHUB_ENV
          echo "AppSettings__JwtSettings__Audience=${{ secrets.AppSettings__JwtSettings__Audience }}" >> $GITHUB_ENV
          echo "AppSettings__JwtSettings__Key=${{ secrets.AppSettings__JwtSettings__Key }}" >> $GITHUB_ENV
          echo "ConnectionStrings__NotesDatabase=${{ secrets.ConnectionStrings__NotesDatabase }}" >> $GITHUB_ENV
      - name: deploy
        run: |
          docker-compose up -d
